"""Updated users table

Revision ID: 4845904fab22
Revises: 5370a890e6ed
Create Date: 2026-07-27 23:46:20.958249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

userrole = postgresql.ENUM(
    "USER",
    "ADMIN",
    name="userrole"
)

# revision identifiers, used by Alembic.
revision: str = '4845904fab22'
down_revision: Union[str, Sequence[str], None] = '5370a890e6ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    userrole.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'evidence',
        sa.Column('file_hash', sa.String(length=64), nullable=False)
    )

    op.alter_column(
        'evidence',
        'generated_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True
    )

    op.drop_constraint(op.f('evidence_hash_key'), 'evidence', type_='unique')
    op.create_unique_constraint(None, 'evidence', ['file_hash'])
    op.drop_column('evidence', 'hash')

    op.add_column(
        'users',
        sa.Column(
            'role',
            userrole,
            nullable=False,
            server_default='USER'
        )
    )

    op.alter_column(
        'users',
        'role',
        server_default=None
    )

    op.add_column(
        'users',
        sa.Column('is_active', sa.Boolean(), nullable=False)
    )

    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(
        op.f('users_email_key'),
        'users',
        ['email'],
        postgresql_nulls_not_distinct=False
    )

    op.drop_column('users', 'is_active')
    op.drop_column('users', 'role')

    # Drop the PostgreSQL enum type
    userrole.drop(op.get_bind(), checkfirst=True)

    op.add_column(
        'evidence',
        sa.Column('hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False)
    )

    op.drop_constraint(None, 'evidence', type_='unique')
    op.create_unique_constraint(
        op.f('evidence_hash_key'),
        'evidence',
        ['hash'],
        postgresql_nulls_not_distinct=False
    )

    op.alter_column(
        'evidence',
        'generated_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False
    )

    op.drop_column('evidence', 'file_hash')
    # ### end Alembic commands ###
