"""Add ai_explanation to reports

Revision ID: e06e16a8343a
Revises: e1f8a0f22608
Create Date: 2026-08-03 11:02:18.232259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e06e16a8343a'
down_revision: Union[str, Sequence[str], None] = 'e1f8a0f22608'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('ai_explanation', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'ai_explanation')
    # ### end Alembic commands ###
