"""adding evidence creation

Revision ID: e1f8a0f22608
Revises: d27e677bb4f9
Create Date: 2026-07-30 22:52:28.398732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1f8a0f22608'
down_revision: Union[str, Sequence[str], None] = 'd27e677bb4f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evidence', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('pdfs', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pdfs', 'created_at')
    op.drop_column('evidence', 'created_at')
    # ### end Alembic commands ###
